name: autofix.ci

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      
      - name: Install oxfmt
        run: npm install --save-dev oxfmt
      
      - name: Run formatter
        run: npx oxfmt
      
      - name: Run autofix.ci
        uses: autofix-ci/action@v1
